parameters:
    app_env: "%env(resolve:APP_ENV)%"
    api_harvest_mode: "%env(resolve:API_HARVEST_MODE)%"

    public_path: "%env(resolve:ENCORE_PUBLIC_PATH)%"
    assets_directory: "%kernel.project_dir%/assets"

    iam_url: "%env(resolve:IAM_URL)%"
    iam_realm: "%env(resolve:IAM_REALM)%"
    iam_client_id: "%env(resolve:IAM_CLIENT_ID)%"
    iam_client_secret: "%env(resolve:IAM_CLIENT_SECRET)%"
    iam_login_disabled: "%env(resolve:IAM_LOGIN_DISABLED)%"

    sandbox_service_account:
        client_id: "%env(resolve:SANDBOX_SERVICE_ACCOUNT_CLIENT_ID)%"
        client_secret: "%env(resolve:SANDBOX_SERVICE_ACCOUNT_CLIENT_SECRET)%"

    sandbox:
        community_id: "%env(resolve:SANDBOX_COMMUNITY_ID)%"
        processings:
            int_vect_files_db: "%env(resolve:SANDBOX_PROC_INT_VECT_FILES_DB)%"
            create_vect_pyr: "%env(resolve:SANDBOX_PROC_CREATE_VECT_PYR)%"
            create_rast_pyr: "%env(resolve:SANDBOX_PROC_CREATE_RAST_PYR)%"

    config:
        community_id: "%env(resolve:CONFIG_COMMUNITY_ID)%"
        technical_name: "%env(resolve:CONFIG_TECHNICAL_NAME)%"

    api_entrepot_url: "%env(resolve:API_ENTREPOT_URL)%"
    annexes_url: "%env(resolve:ANNEXES_URL)%"

    http_proxy: "%env(resolve:HTTP_PROXY)%"
    no_proxy: "%env(resolve:NO_PROXY)%"

    var_data_path: "%kernel.project_dir%/var/data"
    upload_path: "%var_data_path%/uploaded_files"
    style_files_path: "%var_data_path%/style_files"
    capabilities_path: "%var_data_path%/capabilities"
    metadata_path: "%var_data_path%/metadata"
    datasheet_documents_path: "%var_data_path%/datasheet_documents"

    support_contact_mail: "%env(resolve:SUPPORT_CONTACT_EMAIL)%"
    mailer_sender_address: "%env(resolve:MAILER_SENDER_ADDRESS)%"

    api_entrepot:
        processings:
            int_vect_files_db: "%env(resolve:API_ENTREPOT_PROC_INT_VECT_FILES_DB)%"
            create_vect_pyr: "%env(resolve:API_ENTREPOT_PROC_CREATE_VECT_PYR)%"
            create_rast_pyr: "%env(resolve:API_ENTREPOT_PROC_CREATE_RAST_PYR)%"

    api_espaceco_url: "%env(resolve:API_ESPACE_COLLABORATIF_URL)%"
    catalogue_url: "%env(resolve:CATALOGUE_URL)%"
